import sys
from unittest.mock import MagicMock
import json

# --- Mocks ---
mock_google = MagicMock()
mock_adk = MagicMock()
mock_google.adk = mock_adk
sys.modules["google"] = mock_google
sys.modules["google.adk"] = mock_adk
mock_google.__path__ = []
mock_adk.__path__ = []

# Mock google.genai
mock_genai = MagicMock()
sys.modules["google.genai"] = mock_genai
sys.modules["google.genai.types"] = MagicMock()

# Mock config
mock_config = MagicMock()
mock_config.PROJECT_ID = "mock-project-id"
mock_config.LOCATION = "us-central1"
mock_config.GEMINI_MODEL_NAME = "gemini-2.5-pro"
mock_config.IMAGEN_MODEL_NAME = "imagen-3.0-generate-001"
sys.modules["app.config"] = mock_config

# Mock schema
class MockBaseModel:
    def __init__(self, **kwargs):
        for k, v in kwargs.items():
            setattr(self, k, v)
    def model_dump_json(self):
        return json.dumps(self.__dict__, default=lambda o: o.__dict__ if hasattr(o, "__dict__") else str(o))

mock_pydantic = MagicMock()
mock_pydantic.BaseModel = MockBaseModel
sys.modules["pydantic"] = mock_pydantic

try:
    from app.sub_agents.fashion_photographer import FashionPhotographer
    from app.schema import Trend, TaxonomyAttributes
except ImportError as e:
    print(f"Import Error: {e}")
    sys.exit(1)

# Mock ArtDirector
mock_art_director_module = MagicMock()
sys.modules["app.sub_agents.art_director"] = mock_art_director_module
mock_art_director_cls = MagicMock()
mock_art_director_module.ArtDirector = mock_art_director_cls
mock_art_director_instance = mock_art_director_cls.return_value
mock_art_director_instance.create_campaign_directive.return_value = "A high fashion photo generated by Art Director."

# Mock GenAI Client for Imagen
mock_client_cls = sys.modules["google.genai"].Client
mock_client_instance = mock_client_cls.return_value

# Mock Gemini Response (Prompt Generation)
mock_gemini_response = MagicMock()
mock_gemini_response.text = "A high fashion photo of a model wearing the product in a subway station. Neon lighting."
mock_client_instance.models.generate_content.return_value = mock_gemini_response

# Mock Imagen Response (Image Generation)
mock_imagen_response = MagicMock()
mock_generated_image = MagicMock()
mock_generated_image.image_bytes = b"fake_image_bytes"
# If the code uses .image.image_bytes or just .image_bytes, we might need to adjust.
# The code checks for hasattr(generated_image, "image") then .image.image_bytes
# Or hasattr .image_bytes. 
# Let's mock .image_bytes directly as fallback or .image wrapper.
class MockImageWrapper:
    image_bytes = b"fake_image_bytes"
    
mock_generated_image.image = MockImageWrapper()
mock_imagen_response.generated_images = [mock_generated_image]
mock_client_instance.models.generate_images.return_value = mock_imagen_response

print("\n--- Testing FashionPhotographer ---")
try:
    photographer = FashionPhotographer()
    print("FashionPhotographer initialized.")
    
    # Create dummy Trend Data
    # Create dummy Trend Data
    trend_data = Trend(
        executive_summary="Summary",
        trend_name="Subway Core",
        key_designers=[],
        social_media_tags=[],
        key_influencer_handles=[],
        essential_look_characteristics={},
        taxonomy_attributes=TaxonomyAttributes(
            primary_aesthetic="Urban",
            secondary_aesthetic="Gritty",
            key_garments=["Hoodie"],
            materials_and_textures=["Cotton"],
            color_palette=["Grey"],
            mood_keywords=["Neon"],
            target_occasion=["Street"],
            seasonality="FW25"
        ),
        search_vectors=["subway"],
        marketing_attributes=None
    )
    
    # Create a dummy image file for testing
    with open("dummy_product.png", "wb") as f:
        f.write(b"dummy_image_data")
        
    print("Calling generate_campaign_image...")
    output_path = photographer.generate_campaign_image("dummy_product.png", trend_data)
    
    print(f"Generated Image Path: {output_path}")

    if output_path and "generated_campaigns" in output_path:
        print("Success: Image path returned.")
    else:
        print("Failure: No image path returned.")

    # Verify ArtDirector Call
    mock_art_director_instance.create_campaign_directive.assert_called_once()
    
    # Verify Imagen Call
    mock_client_instance.models.generate_images.assert_called_once()
    _, call_kwargs = mock_client_instance.models.generate_images.call_args
    if call_kwargs['prompt'] == "A high fashion photo generated by Art Director.":
        print("Imagen called with correct prompt from ArtDirector.")
    else:
        print("Imagen prompt mismatch.")

except Exception as e:
    print(f"Test failed: {e}")
    import traceback
    traceback.print_exc()
finally:
    import os
    if os.path.exists("dummy_product.png"):
        os.remove("dummy_product.png")
    # Clean up generated campaigns if needed, but safe to leave for manual inspection if real run
    # For test we normally clean up, but here we mocked saving partially
