import sys
from unittest.mock import MagicMock
import json

# --- Mocks ---
mock_google = MagicMock()
mock_adk = MagicMock()
mock_google.adk = mock_adk
sys.modules["google"] = mock_google
sys.modules["google.adk"] = mock_adk
mock_google.__path__ = []
mock_adk.__path__ = []

# Mock google.genai
mock_genai = MagicMock()
sys.modules["google.genai"] = mock_genai
sys.modules["google.genai.types"] = MagicMock()

# Mock config
mock_config = MagicMock()
mock_config.PROJECT_ID = "mock-project-id"
mock_config.LOCATION = "us-central1"
mock_config.GEMINI_MODEL_NAME = "gemini-2.5-pro"
mock_config.STANDARD_GENERATION_CONFIG = {}
sys.modules["app.config"] = mock_config

# Mock schema
class MockBaseModel:
    def __init__(self, **kwargs):
        for k, v in kwargs.items():
            setattr(self, k, v)
    def model_dump_json(self):
        return json.dumps(self.__dict__, default=lambda o: o.__dict__ if hasattr(o, "__dict__") else str(o))

mock_pydantic = MagicMock()
mock_pydantic.BaseModel = MockBaseModel
sys.modules["pydantic"] = mock_pydantic

try:
    from app.sub_agents.art_director import ArtDirector
    from app.schema import Trend
except ImportError as e:
    print(f"Import Error: {e}")
    sys.exit(1)

# Mock GenAI Client
mock_client_cls = sys.modules["google.genai"].Client
mock_client_instance = mock_client_cls.return_value

# Mock Gemini Response
mock_response = MagicMock()
mock_response.text = "A high fashion prompt generated by Art Director."
mock_client_instance.models.generate_content.return_value = mock_response

print("\n--- Testing ArtDirector ---")
try:
    director = ArtDirector()
    print("ArtDirector initialized.")
    
    # Create dummy Trend Data
    trend_data = Trend(
        trend_name="Trend A",
        executive_summary="Desc",
        key_designers=[],
        social_media_tags=[],
        key_influencer_handles=[],
        essential_look_characteristics={},
        search_vectors=["vector"],
        taxonomy_attributes=MagicMock(),
        marketing_attributes=None
    )
    
    # Test create_campaign_directive
    print("Calling create_campaign_directive...")
    prompt = director.create_campaign_directive("dummy_image.png", trend_data)
    
    print(f"Generated Prompt: {prompt}")

    if prompt == "A high fashion prompt generated by Art Director.":
        print("Success: Prompt matched.")
    else:
        print("Failure: Prompt mismatch.")

    # Verify Gemini Call
    mock_client_instance.models.generate_content.assert_called_once()
    
except Exception as e:
    print(f"Test failed: {e}")
    import traceback
    traceback.print_exc()
